### ISSUE TITLE
Waka readme not updating automatically.

### ISSUE THREAD

**Issue by chitraarasu** [athul/waka-readme#85] opened 2022-08-06 03:38 UTC
![Screenshot 2022-08-06 085614](https://user-images.githubusercontent.com/75994428/183231880-53996c39-c805-4b48-9e33-ba880c726d87.png)

## So far it has worked perfectly. Since last week it is not run automatically. it is failed. If I run it manually it works perfectly. Is there any way to fix this?

![Screenshot 2022-08-06 090440](https://user-images.githubusercontent.com/75994428/183232021-631d4f34-eb8a-413c-8b2b-2e9a04e7aff1.png)

## It is my code.

![Screenshot 2022-08-06 090936](https://user-images.githubusercontent.com/75994428/183232182-9a331c6b-e82b-46c4-b7db-1d82f9a000be.png)

**Comment by joe733** [comment] 2022-08-06 04:03
Hi, thanks for bringing this up. I see the same issue with [athurl's](https://github.com/athul/athul/actions) runs and [mine](https://github.com/joe733/joe733/actions). They started failing precisely 7 days ago. But the last merge commit was made 14 days ago. Let me investigate. Maybe something in the upstream changed.

**Comment by joe733** [comment] 2022-08-06 07:07
[WakaTime status](https://status.wakatime.com/) looks good. Looks like an issue with [GitHub status](https://www.githubstatus.com/history) (networking arena probably?). They seem to have a couple of issues for the past few weeks. Closing this for now. Feel free to bump this thread, if the issue is persistent next week.

**Closed by joe733** 2022-08-06 07:07 UTC
Labels: wontfix

**Comment by yasandev** [comment] 2022-08-12 13:24
I have the same issue, and it's been happening long before 2 weeks ago. I usually end up manually updating it every few days.

I initially thought the issue only happens at the specific time I have set up my action to run every day but even after that it kept happening.

https://github.com/yasandev/yasandev/actions
